name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: login to dockerhub 
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_NAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWD}}
      run: docker login -u ${DOCKER_USERNAME} -p  ${DOCKER_PASSWORD}
     
    - name: Build the Docker image
      run: docker build -t ${{secrets.DOCKER_NAME}}/django-notes-app:latest .


    - name: Push the Docker image
      run: docker push ${{secrets.DOCKER_NAME}}/django-notes-app:latest
      
