name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: login to dockerhub 
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_NAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWD}}
      run: docker login -u "${DOCKER_USERNAME}" --password-stdin "${DOCKER_PASSWORD}"
     
    - name: Tag the Docker image with a unique tag
      run: docker tag vaibhav0342/notes-app:latest vaibhav0342/notes-app:$(date +%s)

  
    - name: Push the Docker image with the unique tag
      run: docker push vaibhav0342/notes-app:$(date +%s)

      
      
